Coordinate Reference System
o2r-project/geoextent pull request #110
Opened 2021-01-04 16:53 UTC by SbastianGarzon

Fixes #109

- CRS output correspond to the transformation into WGS84. 
- Tests include CRS assessment

2021-01-04 17:06 UTC, SbastianGarzon commented on tests/test_api.py
> +def test_kml_extract_tbox():
KML time extraction was implemented by #99.
This test is included to properly close #103

2021-01-05 09:42 UTC, nuest requested changes
Had a few comments, but nothing really critical.

I created a couple of issues/comments while thinking about the changes, for later: #111 #112 https://github.com/o2r-project/geoextent/issues/80#issuecomment-754523983

2021-01-05 09:42 UTC, nuest commented on tests/test_cli.py
> +        "bboxes and time values of all files inside folder, are printed to console"
The assert message does not match what is asserted - no time values checked here!

2021-01-05 09:42 UTC, nuest commented on tests/test_cli.py
> +    assert "[292063.81225905, 5618144.09259115, 302531.3161606, 5631223.82854667]" in ret.stdout, \
The assert message does not match what is asserted - no time values checked here!

Also, why would all these coordinates be put out here?

2021-01-05 13:34 UTC, SbastianGarzon commented on geoextent/lib/handleCSV.py
> +        bbox = [minlon, minlat, maxlon, maxlat]
`handleCSV` is not using GDAL. However it would be a good idea to explore the possibility to use `handleVector` for csv files #114

2021-01-05 13:41 UTC, nuest commented on geoextent/lib/handleCSV.py
> +        bbox = [minlon, minlat, maxlon, maxlat]
Loading the CSV through GDAL could be a solution - see also #37 

The CSV handler probably tries way to hard to support very rare edge cases anyway!

However, note that I did not say `handleCSV` should use GDAL, but that we need to make sure that the coordinate order we use here matches the output CRS. If the output CRS is fixed - fine. But if the output CRS can be changed by the user #109 then we need to find out how to create the bounding box here.

Long story short: please double check here that the coordinate order is correct for our output CRS and make a source code comment about the fixed coordinate order.

2021-01-05 13:49 UTC, SbastianGarzon commented on geoextent/lib/handleRaster.py
> +    spatialExtent = {"bbox": bbox, "crs": str(hf.WGS84_EPSG_ID)}
Getting the value from new_crs seems like the best option, however due to the differences between GDAL versions I can not access the EPSG code from the osr.SpatialReference() class.

2021-01-05 13:56 UTC, SbastianGarzon commented on geoextent/lib/handleVector.py
> +                    logger.debug("Time_list: {}".format(time_list))
I forgot to delete this, I was using it for debugging. This is a list of all the timestamps detected in the file. I think it is not necessary to add this, but could be useful a message with the length of the list.

2021-01-05 14:33 UTC, SbastianGarzon commented on geoextent/lib/handleVector.py
> +    if bbox_merge is not None:
I need to modify the behavior of ` fromDirectory()`, but it is a good idea !

2021-01-05 15:56 UTC, nuest requested changes
Final small change: please document the origin of the test file `ifgi_denkpause.xx`.

Good job addressing all the other comments :rocket: :exclamation:

2021-01-05 17:44 UTC, nuest approved these changes

2021-01-05 17:44 UTC, merged